### PR TITLE
"Fix" garrison location

### PR DESCRIPTION
**Pull request by stoglim**
https://github.com/Ravendwyr/Chinchilla/issues/53

This is a really ugly, really quick and dirty "fix" (ok workaround) for what Blizzard is doing.  Basically wait until Blizzard moves it and move it back.

### CODE REVIEW

**Comment by stoglim** [comment]
Upon further testing this is incomplete.  The garrison button is reset upon changing instances... will need to add an event for that just to reposition it....

**Comment by stoglim** [comment]
Still testing, but this appears to keep the button where we want it.

**Comment by Katuras** [comment]
Still same problem with garrison minimap button...

**Comment by stoglim** [comment]
I'm still attempting to ascertain which event is triggering that to be moved out of place.  This PR is an attempt to correct for it, but there still are situations where the Garrison button is moved... until Area change fires again...

**Comment by stoglim** [comment]
DO NOT MERGE at this time.  Going to move logic from the Appearance module to the MoveButtons module and (hopefully) get to the bottom of when these are being improperly moved.

**Comment by stoglim** [comment]
Much cleaner.

**Pull request merged**
