### PR TITLE
SL Beta update and added ability to resize minimap

### PR DESCRIPTION
**Pull request by Thrayl**
Please see above for changes, feel free to discard if you do not want to use :)

### CODE REVIEW

**Comment by fsfod** [comment]
It looks like only one module was fixed, many of the other modules need updated for frame backdrop changes as well.

**Comment by Thrayl** [comment]
https://drive.google.com/file/d/1Sdcs-Vwt_NeyuFUAvKr9HeV2_HaLAtRa

GitHub isn't playing nice with me today, please see attached file. This is
currently working with the changes.

**Comment by l3uGsY** [comment]
> GitHub isn't playing nice with me today, please see attached file. This is currently working with the changes.

Unsure if this is what you were asking for, but I used the zip in game.  Here are the errors.
```
Message: Interface\AddOns\Chinchilla\Modules\Coordinates.lua:59: attempt to call method 'SetBackdrop' (a nil value)
Time: Wed Oct 14 23:02:37 2020
Count: 1
Stack: Interface\AddOns\Chinchilla\Modules\Coordinates.lua:59: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\Chinchilla\Modules\Coordinates.lua"]:59: in function <Interface\AddOns\Chinchilla\Modules\Coordinates.lua:49>
[string "=[C]"]: ?
[string "@Interface\AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface\AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:620: in function <...AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:495: in function `UIParentLoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:542: in function `CombatLog_LoadUI'
[string "@Interface\FrameXML\UIParent.lua"]:1375: in function <Interface\FrameXML\UIParent.lua:1258>

Locals: <none>
```
```
Message: Interface\AddOns\Chinchilla\Modules\Location.lua:43: attempt to call method 'SetBackdrop' (a nil value)
Time: Wed Oct 14 23:02:37 2020
Count: 1
Stack: Interface\AddOns\Chinchilla\Modules\Location.lua:43: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\Chinchilla\Modules\Location.lua"]:43: in function <Interface\AddOns\Chinchilla\Modules\Location.lua:33>
[string "=[C]"]: ?
[string "@Interface\AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface\AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:620: in function <...AddOns\Chinchilla\Libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:495: in function `UIParentLoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:542: in function `CombatLog_LoadUI'
[string "@Interface\FrameXML\UIParent.lua"]:1375: in function <Interface\FrameXML\UIParent.lua:1258>

Locals: <none>
```

**Comment by Thrayl** [comment]
I've submitted PRs for both affected files and also updated the archive that I linked earlier. Please redownload, new version should work without errors.

**Comment by l3uGsY** [comment]
Tried both new profile and existing.  

```
Message: ...la\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:189: attempt to call method 'SetBackdrop' (a nil value)
Time: Wed Oct 14 23:25:20 2020
Count: 2
Stack: ...la\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:189: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua"]:189: in function `?'
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\AceGUI-3.0.lua"]:108: in function <...ace\AddOns\Chinchilla\Libs\AceGUI-3.0\AceGUI-3.0.lua:97>
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\AceGUI-3.0.lua"]:146: in function `Create'
[string "@Interface\AddOns\Chinchilla\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1912: in function `Open'
[string "@Interface\AddOns\Chinchilla\Chinchilla.lua"]:53: in function `OpenConfig'
[string "@Interface\AddOns\Chinchilla\Chinchilla.lua"]:38: in function <Interface\AddOns\Chinchilla\Chinchilla.lua:35>
[string "=(tail call)"]: ?

Locals: frame = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = <table> {
 bgFile = "Interface\DialogFrame\UI-DialogBox-Background"
 tileSize = 32
 edgeFile = "Interface\DialogFrame\UI-DialogBox-Border"
 tile = true
 edgeSize = 32
 insets = <table> {
 }
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
CreateFrame = <function> defined =[C]:-1
UIParent = UIParent {
 0 = <userdata>
 firstTimeLoaded = 1
 variablesLoaded = true
}
FrameBackdrop = <table> {
 bgFile = "Interface\DialogFrame\UI-DialogBox-Background"
 tileSize = 32
 edgeFile = "Interface\DialogFrame\UI-DialogBox-Border"
 tile = true
 edgeSize = 32
 insets = <table> {
 }
}
Frame_OnShow = <function> defined @Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:28
Frame_OnClose = <function> defined @Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:32
Frame_OnMouseDown = <function> defined @Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:36
Button_OnClick = <function> defined @Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:23
PaneBackdrop = <table> {
 bgFile = "Interface\ChatFrame\ChatFrameBackground"
 tileSize = 16
 edgeFile = "Interface\Tooltips\UI-Tooltip-Border"
 tile = true
 edgeSize = 16
 insets = <table> {
 }
}
StatusBar_OnEnter = <function> defined @Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:71
StatusBar_OnLeave = <function> defined @Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:75
Title_OnMouseDown = <function> defined @Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:40
MoverSizer_OnMouseUp = <function> defined @Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:45
SizerSE_OnMouseDown = <function> defined @Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:56
SizerS_OnMouseDown = <function> defined @Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:61
SizerE_OnMouseDown = <function> defined @Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:66
Type = "Frame"
pairs = <function> defined =[C]:-1
methods = <table> {
 OnHeightSet = <function> defined @Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:108
 OnRelease = <function> defined @Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:93
 OnWidthSet = <function> defined @Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:98
 SetStatusText = <function> defined @Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:123
 OnAcquire = <function> defined @Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:83
 Show = <function> defined @Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-Frame.lua:131
 Ena
```

**Comment by Thrayl** [comment]
This is an issue with the ace libraries, I've repackaged the new version of ace3 in the zip above. please try again and advise.

**Comment by l3uGsY** [comment]
We have settings.  Nice work Thrayl.  Few errors pop up when loading coordinates and location. Missions Icon appears in the middle the map, enabling "Move Buttons" does correct this, disabling it sends it to the bottom left of the minimap.  Tracking dots are still suggesting we are being invaded by Legion Cruise Ships  :) 

Here are the error codes for the coordinates and location, respectively.
```
Message: ...la\Libs\AceGUI-3.0-SharedMediaWidgets\prototypes.lua:119: attempt to call method 'SetBackdrop' (a nil value)
Time: Wed Oct 14 23:53:10 2020
Count: 1
Stack: ...la\Libs\AceGUI-3.0-SharedMediaWidgets\prototypes.lua:119: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0-SharedMediaWidgets\prototypes.lua"]:119: in function `GetBaseFrameWithWindow'
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0-SharedMediaWidgets\BackgroundWidget.lua"]:199: in function `?'
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\AceGUI-3.0.lua"]:108: in function <...ace\AddOns\Chinchilla\Libs\AceGUI-3.0\AceGUI-3.0.lua:97>
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\AceGUI-3.0.lua"]:146: in function `Create'
[string "@Interface\AddOns\Chinchilla\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1095: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1092>
[string "@Interface\AddOns\Chinchilla\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1281: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1117>
[string "@Interface\AddOns\Chinchilla\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1648: in function `FeedGroup'
[string "@Interface\AddOns\Chinchilla\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1573: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1557>
[string "=[C]"]: ?
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\AceGUI-3.0.lua"]:72: in function <...ace\AddOns\Chinchilla\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\AceGUI-3.0.lua"]:306: in function `Fire'
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua"]:512: in function `SetSelected'
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua"]:189: in function <...ibs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:185>

Locals: <none>
```
```
Message: ...la\Libs\AceGUI-3.0-SharedMediaWidgets\prototypes.lua:119: attempt to call method 'SetBackdrop' (a nil value)
Time: Wed Oct 14 23:53:27 2020
Count: 2
Stack: ...la\Libs\AceGUI-3.0-SharedMediaWidgets\prototypes.lua:119: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0-SharedMediaWidgets\prototypes.lua"]:119: in function `GetBaseFrameWithWindow'
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0-SharedMediaWidgets\BackgroundWidget.lua"]:199: in function `?'
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\AceGUI-3.0.lua"]:108: in function <...ace\AddOns\Chinchilla\Libs\AceGUI-3.0\AceGUI-3.0.lua:97>
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\AceGUI-3.0.lua"]:146: in function `Create'
[string "@Interface\AddOns\Chinchilla\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1095: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1092>
[string "@Interface\AddOns\Chinchilla\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1281: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1117>
[string "@Interface\AddOns\Chinchilla\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1648: in function `FeedGroup'
[string "@Interface\AddOns\Chinchilla\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1573: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1557>
[string "=[C]"]: ?
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\AceGUI-3.0.lua"]:72: in function <...ace\AddOns\Chinchilla\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\AceGUI-3.0.lua"]:306: in function `Fire'
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua"]:512: in function `SetSelected'
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua"]:189: in function <...ibs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:185>

Locals: <none>
```

**Comment by Thrayl** [comment]
Could you do me a favour and disable all other addons and try? I feel like another addon may be tainting the ace libraries with old code.

**Comment by l3uGsY** [comment]
They are all disabled, just Chinchilla is running. I'll remove configs from WTF and reload from scratch.

**Comment by l3uGsY** [comment]
Same errors, I even remade my interface folder with just Chinchilla and deleted all previous configs.

**Comment by l3uGsY** [comment]
Looks like I missed one item in the settings that was giving an error, perhaps this might help locate the issue.

```
Message: ...la\Libs\AceGUI-3.0-SharedMediaWidgets\prototypes.lua:119: attempt to call method 'SetBackdrop' (a nil value)
Time: Thu Oct 15 00:05:12 2020
Count: 1
Stack: ...la\Libs\AceGUI-3.0-SharedMediaWidgets\prototypes.lua:119: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0-SharedMediaWidgets\prototypes.lua"]:119: in function `GetBaseFrameWithWindow'
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0-SharedMediaWidgets\BackgroundWidget.lua"]:199: in function `?'
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\AceGUI-3.0.lua"]:108: in function <...ace\AddOns\Chinchilla\Libs\AceGUI-3.0\AceGUI-3.0.lua:97>
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\AceGUI-3.0.lua"]:146: in function `Create'
[string "@Interface\AddOns\Chinchilla\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1095: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1092>
[string "@Interface\AddOns\Chinchilla\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1281: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1117>
[string "@Interface\AddOns\Chinchilla\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1648: in function `FeedGroup'
[string "@Interface\AddOns\Chinchilla\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:1573: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1557>
[string "=[C]"]: ?
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\AceGUI-3.0.lua"]:72: in function <...ace\AddOns\Chinchilla\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\AceGUI-3.0.lua"]:306: in function `Fire'
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua"]:512: in function `SetSelected'
[string "@Interface\AddOns\Chinchilla\Libs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua"]:189: in function <...ibs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:185>

Locals: <none>
```

**Comment by Thrayl** [comment]
Ill have to have a look into this one. I can't reproduce the issue on my end.

**Comment by l3uGsY** [comment]
Here, I made a small video.  Perhaps I did something wrong.

https://youtu.be/FbVp9l8uPGY

**Comment by Thrayl** [comment]
image

This is what I get when I start with a totally fresh interface. I'm really unsure how your client is making such a mess of it. Are you on enUS or a non english client?

**Comment by l3uGsY** [comment]
enUS :(  I will download the copy again from your drop.

**Comment by Thrayl** [comment]
> Here, I made a small video. Perhaps I did something wrong.
> 
> https://youtu.be/FbVp9l8uPGY

I've isolated a bug based on this. I'm working on it now :)

**Comment by Thrayl** [comment]
Please re-download and check *fingers crossed*

**Comment by l3uGsY** [comment]
> 
> 
> Please re-download and check _fingers crossed_

All is well, no more errors.

https://youtu.be/V38C3-e6cJE

**Comment by l3uGsY** [comment]
Amazing work, thank you so much for putting your time into this.  💯

**Comment by Ravendwyr** [comment]
Closing this for now due to merge issues, though I may still add in the height/width options in the future. There's another minor issue I discovered while testing this though and I'd like to look into that first.

**Pull request closed without merging**
